Repository edmcouncil/html-pages, pull requests merged in 2022-09, with the labels that each got.

#243 Search results unclickable
  auto/src/views/Ontology.vue
  fibo/src/views/Ontology.vue
  idmp/src/views/Ontology.vue
Labels: bug

#247 Security fixes for strapi framework
  general/package-lock.json
  general/package.json
Labels: dependencies

#249 Fix problem with downloading files in wrong location
  .gitignore
  general/api/strapi.js
  general/components/Articles/ImageTextSection.vue
  general/nuxt.config.js
Labels: bug

#252 Empty diagrams
  general/components/VisNetwork.vue
  general/pages/_.vue
Labels: bug, diagram

#255 Fix problem with links in products
  general/components/Articles/SerializationListSection.vue
Labels: bug

#258 New maturity levels display
  general/components/ModuleTree.vue
  general/pages/_.vue
Labels: enhancement

#259 Launching pad for IDMP Ontology
  home/src/components/HeaderComponent.vue
  home/src/components/SlideCarousel.vue
  home/src/views/Home.vue
Labels: enhancement
