Repository edmcouncil/html-pages, pull requests merged in 2023-01, with the labels that each got.

#314 References to outboundClick removed from general
  general/components/Articles/DownloadSection.vue
  general/components/Articles/TableListSection.vue
Labels: bug

#319 Time instances for ontology products
  general/components/Articles/SerializationListSection.vue
Labels: enhancement

#324 html-pages hardcoded URLs (WIP)
  general/api/strapi.js
  general/components/Articles/SerializationListSection.vue
  general/components/FooterComponent.vue
  general/components/HeaderComponent.vue
  general/components/Ontology/GraphGuide.vue
  general/components/Ontology/GraphVisualization.vue
  general/components/Ontology/OntologyDownload.vue
  general/components/SlideCarousel.vue
  general/components/StatsComponent.vue
  general/components/VisNetwork.vue
  general/components/chunks/LangCodeFlags.vue
  general/components/chunks/link.vue
  general/nuxt.config.js
  general/pages/_.vue
  general/pages/index.vue
  general/pages/page/_slug.vue
  general/pages/release-notes.vue
  general/store/configuration.js
  general/store/helpers.js
  general/store/index.js
  general/store/servers.js
Labels: bug, enhancement
